# -*- coding: utf-8 -*-
"""packege.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhITs5TwspW8S3eBljuLN3ihHi31r6Mk
"""

# 패키지 설치
!pip install --upgrade pip
!apt install -y vim # 로컬 진행을 위해 apt -> pip로 변경
!apt install python 3.11

!pip install -q requests pandas numpy python-dotenv